# Generated by Django 5.1.3 on 2024-12-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_color_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
