# Generated by Django 5.1.3 on 2024-12-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_item_color_cart_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='size',
        ),
    ]
