# Generated by Django 5.1.3 on 2024-12-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_item_color_remove_cart_item_size'),
        ('store', '0006_alter_variation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='varitations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
