# Generated by Django 5.1.3 on 2025-01-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_item_varitations'),
        ('store', '0006_alter_variation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='varitations',
            field=models.ManyToManyField(blank=True, null=True, to='store.variation'),
        ),
    ]
