# Generated by Django 5.1.3 on 2025-02-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='is_orderd',
            field=models.BooleanField(default=True),
        ),
    ]
